@startuml
!pragma layout smetana

Object TournamentController
Object Tournament
Object RankList
Object Registration
Object Rounds
Object Players
Object Teams
Object Rank
Object QuarterFinal
Object SemiFinal
Object Final
Object ScorePoints
Object WinnersAndLosers
Object TournamentPlan
Object Input


TournamentController <|-- Tournament

Tournament *-- Registration
Tournament *-- TournamentPlan
Tournament *-- Rounds
Tournament *-- RankList

Registration *--- "8" Teams
Input -> TournamentController

Rounds <-- RankList
Rounds *- "4" QuarterFinal
Rounds *-- "2" SemiFinal
Rounds *-- "1" Final
Rounds o-- Teams
Rounds --o ScorePoints

Teams *-- "2-5" Players

Rank o-- Teams
Rank *-- ScorePoints

QuarterFinal .. SemiFinal
QuarterFinal o--  WinnersAndLosers

SemiFinal .. Final
SemiFinal o--  WinnersAndLosers

Final o-- WinnersAndLosers

@enduml